@Qams.SupplierQuality.Api_HostAddress = http://localhost:5232

GET {{Qams.SupplierQuality.Api_HostAddress}}/health
Accept: application/json

###

GET {{Qams.SupplierQuality.Api_HostAddress}}/api/v1/suppliers
Accept: application/json

###

POST {{Qams.SupplierQuality.Api_HostAddress}}/api/v1/suppliers
Content-Type: application/json
X-Tenant-Id: tenant-life-sciences-demo
X-Idempotency-Key: create-supplier-001

{
  "tenantId": "tenant-life-sciences-demo",
  "name": "Prime Components Ltd.",
  "score": 88,
  "status": "Approved",
  "lastAuditAtUtc": "2026-01-25T14:00:00Z"
}

###

POST {{Qams.SupplierQuality.Api_HostAddress}}/api/v1/suppliers/supplier-0001/score
Content-Type: application/json
X-Tenant-Id: tenant-life-sciences-demo
X-Idempotency-Key: update-supplier-score-001

{
  "tenantId": "tenant-life-sciences-demo",
  "score": 91,
  "status": "Approved",
  "lastAuditAtUtc": "2026-05-03T11:00:00Z"
}
