{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: qams-{{ $name }}
  labels:
    app.kubernetes.io/name: qams-{{ $name }}
    app.kubernetes.io/part-of: qams
spec:
  selector:
    app.kubernetes.io/name: qams-{{ $name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ $service.port }}
---
{{- end }}
